max_width = 80
use_small_heuristics = "max"

# Unfortunately, this feature is only available on nightly. :|  Without it,
# comments can be of arbitrary width (!) so they need to be manually verified.
# wrap_comments = true
