[package]
name = "humpty"
version = "0.1.5"
edition = "2024"

[dependencies]
zerocopy = "0.8.48"
zerocopy-derive = "0.8.48"
static_assertions = { version = "1", default-features = false }
lzss = { version = "0.9", default-features = false }
hubpack = { version = "0.1", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde-big-array = { version = "0.5" }
