[package]
name = "humpty"
version = "0.1.0"
edition = "2018"

[dependencies]
zerocopy = "0.6.1"
static_assertions = { version = "1", default-features = false }
lzss = { version = "0.8", default-features = false }
